#!/bin/bash
echo ""
bin/gn gen out/android-x86-debug --args='ndk="'${ANDROID_NDK_ROOT}'" target_cpu="x86"'
echo ""
echo "Build cmd:"
echo "ninja -C out/android-x86-debug"
echo ""
echo "Create App:"
echo "b/android-x86-debug-app HelloWorld"
echo ""
echo "Deploy to device:"
echo "adb install out/android-x86-debug/HelloWorld.apk"
echo ""
