#!/bin/bash
echo ""
bin/gn gen out/arm64-debug --args='target_os="linux" 
    target_cpu="arm64" 
    extra_cflags = [ "-DSDL_ATOMIC_DISABLED" ]
    cc="clang" cxx="clang++"'
echo ""
echo "Build cmd:"
echo "ninja -C out/arm64-debug"
echo ""
echo "Run Test:"
echo "out/arm64-debug/HelloWorldApp"
echo "out/arm64-debug/TemplateApp"
echo "out/arm64-debug/EdisonApp"
echo ""
