#!/bin/bash

#tools/update_sk_ui
b/macos-x64-debug
ninja -C out/macos-x64-debug 

echo ""
echo "Run Test:"
echo "out/macos-x64-debug/HelloWorld"
echo "out/macos-x64-debug/viewer"
echo ""

PS3='Please enter your choice: '
options=("HelloWorld" "HelloWorldApp" "SkottieViewer" "viewer" "Quit")
select opt in "${options[@]}"
do
    case $opt in
        "HelloWorld")
            out/macos-x64-debug/HelloWorld
            ;;
        "HelloWorldApp")
            out/macos-x64-debug/HelloWorldApp
            ;;
        "SkottieViewer")
            out/macos-x64-debug/SkottieViewerApp
            ;;
        "viewer")
            out/macos-x64-debug/viewer
            ;;
        "Quit")
            break
            ;;
        *) echo "invalid option $REPLY";;
    esac
done
