#!/bin/bash
echo ""
bin/gn gen out/ios-sim-release --args='is_debug=false is_official_build=true target_os="ios" target_cpu="x64" ios_min_target = "13.0"' --ide=xcode
echo ""
echo "Build cmd:"
echo "ninja -C out/ios-sim-release"
echo ""
echo "Deploy to device:"
echo "ios-deploy -b out/ios-sim-release/HelloWorld.app"
echo ""
