#!/bin/bash
echo ""
bin/gn gen out/linux-debug --args='skia_use_gl=true target_os="linux" cc="clang" cxx="clang++"'
echo ""
echo "Build cmd:"
echo "ninja -C out/linux-debug HelloWroldApp"
echo "ninja -C out/linux-debug DemoApp"
echo ""
echo "Run Test:"
echo "out/linux-debug/HelloWroldApp"
echo "out/linux-debug/DemoApp"
echo ""
