#!/bin/bash

b/macos-x64-release
ninja -C out/macos-x64-release 

echo ""
echo 'Press any key to upload.'
read -s 
echo ""

tools/upload-libs-macos
dirsync tools/_liblist ../cstack/tools/_liblist -c -p -s -v 

echo ""
echo 'Press any key to sync.'
read -s 
echo ""

python2 tools/sync-libs.py macos

