#!/bin/bash
echo ""
bin/gn gen out/macos-x64-shared --args="is_debug=false skia_use_metal=true is_official_build=true is_component_build=true skia_enable_skottie=false" --ide=xcode
echo ""
echo "Build cmd:"
echo "export LD_LIBRARY_PATH=`pwd`/out/macos-x64-shared"
echo "ninja -C out/macos-x64-shared"
echo ""
