#!/bin/bash
echo ""
bin/gn gen out/macos-m1-release --args='is_debug=false target_cpu="arm64" skia_use_metal=true is_official_build=true' --ide=xcode
echo ""
echo "Build cmd:"
echo "ninja -C out/macos-m1-release"
echo ""
echo "Run Test:"
echo "out/macos-m1-release/HelloWorld"
echo ""
